---
title: "Basic Analysis Redone"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Defines the thresholds to be county specific
library(tsModel)
library(ggplot2)
library(gnm)
library(splines)
library(AER)
library(cowplot)
library(dplyr)

#Meta-analysis packages
library(metafor)
library(mvmeta)
```

```{r}
#Loading and cleaning the data
dailyCT<-read.csv("/Users/kevin/Documents/ChenLabResearch/HurricaneProject/NCExposureData.csv",header = T)%>% 
  dplyr::select(-X,-caseControl)
dailyCT$date<-as.Date(dailyCT$date)

#Add the 7-14 day lags
dailyCT$prcp95th_lag7 <- tsModel::Lag(dailyCT$prcp95th_lag0, 7, group = as.factor(dailyCT$FIPS))
dailyCT$prcp95th_lag8 <- tsModel::Lag(dailyCT$prcp95th_lag0, 8, group = as.factor(dailyCT$FIPS))
dailyCT$prcp95th_lag9 <- tsModel::Lag(dailyCT$prcp95th_lag0, 9, group = as.factor(dailyCT$FIPS))
dailyCT$prcp95th_lag10 <- tsModel::Lag(dailyCT$prcp95th_lag0, 10, group = as.factor(dailyCT$FIPS))
dailyCT$prcp95th_lag11 <- tsModel::Lag(dailyCT$prcp95th_lag0, 11, group = as.factor(dailyCT$FIPS))
dailyCT$prcp95th_lag12 <- tsModel::Lag(dailyCT$prcp95th_lag0, 12, group = as.factor(dailyCT$FIPS))
dailyCT$prcp95th_lag13 <- tsModel::Lag(dailyCT$prcp95th_lag0, 13, group = as.factor(dailyCT$FIPS))
dailyCT$prcp95th_lag14 <- tsModel::Lag(dailyCT$prcp95th_lag0, 14, group = as.factor(dailyCT$FIPS))

#Now we load the cause specific mortality data
mdata <- read.csv("/Users/kevin/Documents/ChenLabResearch/HurricaneProject/Coding/DataSources/CauseSpecificMortality.csv", header = TRUE)
mdata$date <- as.Date(mdata$date)

#Now we create the temperature lags within each county 
regions <- as.character(unique(dailyCT$FIPS))
dlist <- lapply(regions,function(x) dailyCT[dailyCT$FIPS==x,])
names(dlist) <- regions
for(i in seq(length(dlist))) {
  #Print to keep track of the county we are on
  cat(i,"")
  
  #Extract the data
  data <- dlist[[i]]
  
  #Lags for temperature
  data$templag0<-data$temp
  data$templag1<-runMean(data$temp,0:1)
  data$templag2<-runMean(data$temp,0:2)
  data$templag3<-runMean(data$temp,0:3)
  data$templag4<-runMean(data$temp,0:4)
  data$templag5<-runMean(data$temp,0:5)
  data$templag6<-runMean(data$temp,0:6)
  data$templag7<-runMean(data$temp,0:7)
  data$templag8<-runMean(data$temp,0:8)
  data$templag9<-runMean(data$temp,0:9)
  data$templag10<-runMean(data$temp,0:10)
  data$templag11<-runMean(data$temp,0:11)
  data$templag12<-runMean(data$temp,0:12)
  data$templag13<-runMean(data$temp,0:13)
  data$templag14<-runMean(data$temp,0:14)
  
  #time
  data$time<-c(1:length(data$date))
  
  if(i==1){
    lagresult<-data
  }else{
      lagresult<-rbind(lagresult,data)
  }
}


lagresult<-dplyr::select(lagresult,-totdeath)
alldata<-dplyr::left_join(mdata,lagresult,by=c("FIPS","date"))

#Because we want to get rid of the index column
mydata <- alldata[,-1]
```


```{r}
#Now we run our models using the different mortality types. We define the mortalities and the exposure lags
vars <- c("totdeath")
lags <-  c("prcp95th_0", "prcp95th_1","prcp95th_2","prcp95th_3","prcp95th_4","prcp95th_5","prcp95th_6","prcp95th_7", "prcp95th_8", "prcp95th_9", "prcp95th_10", "prcp95th_11", "prcp95th_12", "prcp95th_13", "prcp95th_14")

#Now define the regions and separate the FIPs in the general data frame into lists
regions <- as.character(unique(mydata$FIPS))
dlist <- lapply(regions,function(x) mydata[mydata$FIPS==x,])
names(dlist) <- regions

#Loop through the different mortalities
mod_results <- data.frame()
for(death_type in vars){
  #Define a data frame to hold all of the moving lag average information for each county
  countyMovingData <- data.frame()
  
  #For loop to loop through the FIPs
  for(i in seq(length(dlist))){
    #Define a data frame to hold the model results for all the moving lag averages
    mLagResults <- data.frame()
    #Print the FIPs as we run through the for loop
    cat(i, "")
    
    #Extract the data
    subdata <- dlist[[i]]
    
    #We need two for loops, one to loop through the moving lags and then an inner one to loop through the precipitation lag days
    mLags <- c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14")
    for(j in mLags){
      print(paste0("Moving lag ", j))
      #Define a data frame to hold the model results for a single moving lag average
      metaresults <- data.frame(cat=lags, fit = NA, se = NA)
      
      #For loop for all of the rainfall lags and one moving lag temperature
      for(t in seq(length(lags))){
        print(paste0("Rainfall lag ", t-1))
        if(death_type == "totdeath"){
          mod1 <- glm(subdata[, death_type] ~ as.factor(subdata[, paste0("prcp95th_lag", t-1)]) 
                  + ns(time, 4*6) + ns(subdata[, paste0("templag", j)], 5) + dow,
                  data = subdata, family = quasipoisson)
        }else{
          trynext = try(
            mod1 <- glm(subdata[, death_type] ~ as.factor(subdata[, paste0("prcp95th_lag", t-1)]) 
                    + ns(time, 4*6) + ns(subdata[, paste0("templag", j)], 5) + dow,
                    data = subdata, family = quasipoisson), silent = F)
        #To get around the algorithm not converging for some counties
          if("try-error" %in% class(trynext)){
            next
          }
          mod1 <- glm(subdata[, death_type] ~ as.factor(subdata[, paste0("prcp95th_lag", t-1)]) 
                      + ns(time, 4*6) + ns(subdata[, paste0("templag", j)], 5) + dow,
                      data = subdata, family = quasipoisson)
        }
        metaresults[t, 2:3] <- c(summary(mod1)$coef[2,1], summary(mod1)$coef[2,2])
        metaresults$dis[t] <- death_type
        metaresults$county[t] <- unique(subdata$FIPS)
        metaresults$lagTemp[t] <- paste0("0", j)
      }
      
      #Rbind the results for all the rainfall lags given a temperature moving lag
      if(j == "0"){
        mLagResults <- metaresults
      }else{
        mLagResults <- rbind(mLagResults, metaresults)
      }
    }
    if(i == 1){
      countyMovingData <- mLagResults
    }else{
      countyMovingData <- rbind(countyMovingData, mLagResults)
    }
  }
  #Now we store them in the general modResults for each mortality type
  if(death_type == "totdeath"){
    mod_results <- countyMovingData
  }else{
    mod_results <- rbind(countyMovingData, mLagResults)
  }
}

#Save it so I don't have to run this ridiculously long code again
output <- mod_results
#output_results <- lapply(vars, function(x) mod_results[mod_results$dis == x, ])
```

```{r}
temp <- output
```

```{r}
#Now we conduct the meta-analysis
#Get rid of the NAs and redefine the lags, vars, along with a new metaresults dataframe
countyresult<-na.omit(temp)

#Define movLags to have the moving lag types in countyresult
movLags <- unique(countyresult$lagTemp)

#Define lags to be the different types of rainfall lags
lags <- unique(countyresult$cat)

#We first need to split the different moving lags into their own list
mvLagResults <- lapply(movLags, function(x) countyresult[countyresult$lagTemp == x, ])
```

```{r}
#Let us create a data frame to hold the meta-analysis of all the prcplags for each moving lag
movingLagFinal <- data.frame()

#First loop through each of the moving lag dataframes
for(i in 1:length(movLags)){
  #First subset the lists to the correct moving lag and print the current moving lag we are on
  cat(movLags[i], "")
  data <- mvLagResults[[i]]
  
  #Now define a data frame to hold the model results for each precipitation lag type
  metaresults <- data.frame(cat=lags, fit = NA, low = NA, upper = NA)
  
  #Now run the meta-analysis model on each lag
  for(j in seq(length(lags))){
    #Print the rainfall lag we are on
    cat(j, "")
    #Subset the data further on the rainfall lag
    prcp_lag <- subset(data, data$cat == lags[j])
    
    fit_est <- prcp_lag$fit
    fit_se <- prcp_lag$se
    
    #Now we perform the meta-analysis
    metamod <- rma(yi = fit_est, sei = fit_se, data = prcp_lag, method = "REML")
    metaresults[j, 2] <- predict(metamod, transf = exp, digits = 4)$pred
    metaresults[j, 3] <- predict(metamod, transf = exp, digits = 4)$ci.lb
    metaresults[j, 4] <- predict(metamod, transf = exp, digits = 4)$ci.ub
    
    metaresults$moveLagTemp[1:nrow(metaresults)] <- movLags[i]
    metaresults$thres[1:nrow(metaresults)] <- "95th"
  }
  
  #Now we pass the data into the final data frame
  if(i == 1){
    movingLagFinal <- metaresults
  }else{
    movingLagFinal <- rbind(movingLagFinal, metaresults)
  }
}

holder <- movingLagFinal
holder$Analysis <- "MovingLags"
#write.csv(holder, "/Users/kevin/Documents/ChenLabResearch/HurricaneProject/Coding/PostJournalComments/MovingLags.csv")
```
